version: "3.8"

services:
  app:
    image: ghcr.io/psmty/tsmonitor:latest
    restart: always
    ports:
      - 8080:4321
    networks:
      - internal
    env_file:
      - .env
    depends_on:
      - db # Ensures db container starts before the app
    volumes:
    - ./sites:/app/cache/crawler

  db:
    image: postgres:latest # Use the official PostgreSQL image
    container_name: postgres-db
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # PostgreSQL username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # PostgreSQL password
      POSTGRES_DB: ${POSTGRES_DB} # Name of the database
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data in a Docker volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
