[[d1_databases]]
binding = "DATABASE" # Should match preview_database_id
database_name = "tempus-db"
database_id = "b586bf89-5767-45e2-b441-257748faa614" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DATABASE" # Required for Pages local development